### ISSUE TITLE
Not found in npm

### ISSUE THREAD

**Issue by peternoyes** [mattdesl/canvas-text#1]
It seems that the project is not in npm. Is there any other way I could access this project?

**Comment by mattdesl** [comment]
I haven't published to npm since the current version is still a heavy work in progress and contains some bugs.

**Comment by mattdesl** [comment]
I just pushed `0.x` to npm which is the current unstable and slightly buggy version. Let me know if you'd like to contribute. :smile:

**Comment by peternoyes** [comment]
Thanks! I am trying to open index.html, and it is referencing bundle.js which isn't in the folder. Do I need to run something to generate it?

**Comment by peternoyes** [comment]
I am new to npm. I basically did "npm run build", is that the best way to build?

**Comment by mattdesl** [comment]
After you git clone this repo, you can `npm run start` to start developing - open [http://localhost:9966/](http://localhost:9966/) and change the JS files, and the browser page should refresh. You can use `npm run build` to create a static bundle (i.e. for production).

[Some further reading](https://github.com/Jam3/jam3-lesson-module-basics)
